[window]
padding={x=10,y=10}
dynamic_padding=true
opacity=0.6

[font]
size=11


# Colors 0 through 7
[colors.normal]
black = '#282828'
red = '#ca1444'
green = '#789aba'
yellow = '#b3879f'
blue = '#9556fb'
magenta = '#cb6fa1'
cyan = '#fb6e93'
white = '#eeeeee'

# Colors 8 through 15
[colors.bright]
black = '#98218e'
red = '#cb515d'
green = '#5a87b1'
yellow = '#9c61ab'
blue = '#9a77b1'
magenta = '#f2a297'
cyan = '#f4436f'
white = '#ebdbb2'
